### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by akxcv** [umbrellio/verifly#3]
Xverifier sounds boring, don't you think? Perhaps we should think of a different name. Maybe "verifly"?Probably not the best option, but certainly it's better to work with.

**Comment by JelF** [comment]
ill think about verifly, thanks. Is there another naming suggestions?

**Comment by akxcv** [comment]
Not at the moment, but we definitely should think a little more, at least until first release.

**Comment by JelF** [comment]
It's important to solve it right now, cose we need to publish it on rubygems

**Comment by akxcv** [comment]
I suggest we go with verifly, then.
